### ISSUE TITLE
Any plans to support the equivalent of `GlobalNetworkPolicy` in calico?

### ISSUE THREAD

**Issue by vadasambar** [aws/amazon-network-policy-controller-k8s#126]
We want to migrate from calico to amazon-network-policy-controller-k8s but we don't have a very good substitute for [calico's `GlobalNetworkPolicy`](https://docs.tigera.io/calico/latest/reference/resources/globalnetworkpolicy).

Any suggestions/ideas?

**Comment by vadasambar** [comment]
https://github.com/awslabs/k8s-network-policy-migrator can be used if the number of namespaces are fixed but the namespaces in my case aren't really fixed 😄

**Comment by vadasambar** [comment]
Looks like the migrator doesn't support conversion of calico's `GlobalNetworkPolicy` resource: https://github.com/awslabs/k8s-network-policy-migrator/blob/main/netpolymigrator/calico_utils.py 😓

**Comment by orsenthil** [comment]
We don't have an equivalent of GlobalNetworkPolicy in VPC CNI network policy implementation. The policies should be namespace scoped.

**Comment by orsenthil** [comment]
The equivalent "GlobalNetworkPolicy" will come through AdminNetworkPolicy - https://github.com/aws/containers-roadmap/issues/2243 - which will satisfy Deny traffic at a cluster level / Allow traffic at Cluster Level use cases - which is probably the intention here.  Please follow up on the containers-roadmap item.
